language: go
go:
  - "1.12.5"

notifications:
  email: false

before_install:
  # 把项目文件夹移到GOPATH之外，以方便使用相对路径引入
  - mkdir /home/travis/Tomahawk
  - cp -R /home/travis/gopath/src/github.com/RitterHou/Tomahawk /home/travis
  - cd /home/travis/Tomahawk

# 跳过install阶段
# Reference: https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
install: true

script:
  - ./build.sh --release

before_deploy:
  - mkdir build
  - mv Tomahawk* ./build

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
